//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_SETUP
    {
        public decimal COMP_CODE { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> FORMERLY { get; set; }
        public string FORMERLY_NAME { get; set; }
        public string ABRIVIATION { get; set; }
        public string ADDRESS { get; set; }
        public string ADDRESS_REG { get; set; }
        public string PHONE { get; set; }
        public string UAN { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string NTN { get; set; }
        public Nullable<decimal> LESSOR_CODE { get; set; }
        public string INCOR_NO { get; set; }
        public Nullable<System.DateTime> INCOR_DATE { get; set; }
        public string SERVER_LOCATION { get; set; }
        public Nullable<decimal> SLAB_DAYS { get; set; }
        public string FINYEAR { get; set; }
        public Nullable<System.DateTime> FINYEAR_FROM { get; set; }
        public Nullable<System.DateTime> FINYEAR_TO { get; set; }
        public string GL_YEAR { get; set; }
        public string CURRENT_YEAR { get; set; }
        public Nullable<decimal> GLYEAR_CODE { get; set; }
        public string UN_URL { get; set; }
        public string NACTA_URL { get; set; }
        public string ATL_URL { get; set; }
        public string ATL_PATH { get; set; }
        public string SMS_URL { get; set; }
        public Nullable<decimal> INACTIVE { get; set; }
    }
}
