//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_USER_RIGHT
    {
        public decimal USER_CODE { get; set; }
        public string MID { get; set; }
        public Nullable<decimal> LEVEL_CODE { get; set; }
        public decimal RIGHT_CODE { get; set; }
        public Nullable<decimal> RIGHT_DESC_CODE { get; set; }
        public string RIGHT_DESC { get; set; }
        public string TRAN_MODE { get; set; }
        public decimal TRAN_CODE { get; set; }
        public Nullable<decimal> RIGHT_FLAG { get; set; }
        public string RIGHT_URL { get; set; }
    }
}
