//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_MDL
    {
        public decimal CODE { get; set; }
        public string MID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> ACTIVE_DATE { get; set; }
        public Nullable<decimal> ACTIVE_BY { get; set; }
        public Nullable<decimal> INACTIVE { get; set; }
    }
}
