//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_USER_MDL
    {
        public decimal USER_CODE { get; set; }
        public string MID { get; set; }
        public Nullable<decimal> MID_FLAG { get; set; }
        public string LEVEL_CODE { get; set; }
        public Nullable<decimal> LOGIN { get; set; }
        public Nullable<System.DateTime> LOGIN_ON { get; set; }
        public Nullable<System.DateTime> LOGOUT_ON { get; set; }
        public Nullable<System.DateTime> LAST_LOGIN { get; set; }
        public Nullable<decimal> ATTEMPT { get; set; }
        public Nullable<decimal> LOCK { get; set; }
        public Nullable<System.DateTime> LOCK_DATE { get; set; }
        public Nullable<decimal> DORMANT { get; set; }
        public Nullable<System.DateTime> DORMANT_DATE { get; set; }
        public Nullable<decimal> MIN_RATE { get; set; }
        public Nullable<decimal> MAX_RATE { get; set; }
        public Nullable<decimal> MIN_LIMIT { get; set; }
        public Nullable<decimal> MAX_LIMIT { get; set; }
    }
}
