//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_USER_BRANCH
    {
        public string MID { get; set; }
        public decimal USER_CODE { get; set; }
        public decimal BRANCH_CODE { get; set; }
        public string BRANCH_NAME { get; set; }
        public Nullable<decimal> BRANCH_FLAG { get; set; }
    }
}
