//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_USERS
    {
        public Nullable<System.DateTime> CREATION { get; set; }
        public Nullable<System.DateTime> LAST_MODIFY { get; set; }
        public decimal USER_CODE { get; set; }
        public string EMP_CODE { get; set; }
        public byte[] CODE { get; set; }
        public Nullable<decimal> PASS_EXPIRY_DAYS { get; set; }
        public Nullable<System.DateTime> PASS_CHANGE_DATE { get; set; }
        public Nullable<decimal> DORMANT_DAYS { get; set; }
        public string AUTH_STATUS { get; set; }
        public Nullable<System.DateTime> AUTH_DATE { get; set; }
        public Nullable<decimal> AUTH_BY { get; set; }
        public string AUTH_REMARKS { get; set; }
    }
}
