//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_AUTH_STATUS
    {
        public string CODE { get; set; }
        public string DESC { get; set; }
        public Nullable<decimal> INACTIVE { get; set; }
    }
}
