//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_DEF_INSU_CO
    {
        public decimal CODE { get; set; }
        public string DESC { get; set; }
        public string ADD { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string PERSON_BUS { get; set; }
        public string PERSON_DESIG_BUS { get; set; }
        public string PERSON_ADD_BUS { get; set; }
        public string PERSON_PHONE_BUS { get; set; }
        public string PERSON_CLM { get; set; }
        public string PERSON_DESIG_CLM { get; set; }
        public string PERSON_ADD_CLM { get; set; }
        public string PERSON_PHONE_CLM { get; set; }
        public string AUTH_STATUS { get; set; }
        public Nullable<System.DateTime> AUTH_DATE { get; set; }
        public Nullable<decimal> AUTH_BY { get; set; }
        public string AUTH_REMARKS { get; set; }
        public Nullable<decimal> INACTIVE_LMS { get; set; }
        public Nullable<decimal> INACTIVE_MFS { get; set; }
    }
}
