//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDD_CLIENT_GUA
    {
        public string PARTY_CODE { get; set; }
        public decimal CODE { get; set; }
        public string NAME { get; set; }
        public string ADD { get; set; }
        public string ADD_PREM { get; set; }
        public Nullable<decimal> CNIC { get; set; }
        public Nullable<System.DateTime> CNIC_EXPIRY { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string FATHER { get; set; }
        public string MOTHER { get; set; }
        public string SPOUSE { get; set; }
        public Nullable<decimal> COS { get; set; }
        public string COS_ADD { get; set; }
        public Nullable<decimal> CITY_BIRTH { get; set; }
        public Nullable<decimal> COUNTRY_BIRTH { get; set; }
        public Nullable<decimal> COUNTRY_NATIONAL { get; set; }
        public Nullable<decimal> LIAB_G { get; set; }
        public Nullable<decimal> LIAB_B { get; set; }
        public Nullable<decimal> AUTH_SIGN { get; set; }
    }
}
