//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDD_CLIENT_BANK
    {
        public decimal PARTY_CODE { get; set; }
        public decimal DD_CODE { get; set; }
        public decimal CODE { get; set; }
        public Nullable<decimal> BANK_CODE { get; set; }
        public Nullable<decimal> BANK_BR_CODE { get; set; }
        public string AC_TITLE { get; set; }
        public string AC_NO { get; set; }
        public string JOINT { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> RELATION { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
    }
}
