//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDD_CLIENT_DIR
    {
        public decimal PARTY_CODE { get; set; }
        public decimal DD_CODE { get; set; }
        public decimal CODE { get; set; }
        public string NAME { get; set; }
        public string ADD { get; set; }
        public string ADD_PERM { get; set; }
        public string FATHER { get; set; }
        public string MOTHER { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string MARITAL { get; set; }
        public string SPOUSE { get; set; }
        public Nullable<decimal> CNIC { get; set; }
        public Nullable<System.DateTime> CNIC_EXPIRY { get; set; }
        public string PASST_NO { get; set; }
        public Nullable<System.DateTime> PASS_EXPIRY { get; set; }
        public Nullable<decimal> SHARES { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<System.DateTime> DOL { get; set; }
        public string TYPE { get; set; }
        public string TNOM { get; set; }
        public string NNOM { get; set; }
        public string PROFESSION { get; set; }
        public Nullable<decimal> BIRTH_COUNTRY { get; set; }
        public Nullable<decimal> BIRTH_CITY { get; set; }
        public string BIRTH_PLACE { get; set; }
        public Nullable<decimal> NATIONALITY { get; set; }
        public Nullable<decimal> COS { get; set; }
        public string COS_ADDS { get; set; }
        public string PEP_STATUS { get; set; }
        public string REL_OTHR_ORG { get; set; }
        public Nullable<decimal> AUTH_SIGN { get; set; }
    }
}
