//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDD_CLIENT_CON
    {
        public decimal PARTY_CODE { get; set; }
        public Nullable<decimal> RES_STATUS { get; set; }
        public string FATHER { get; set; }
        public string MOTHER { get; set; }
        public Nullable<decimal> GENDER { get; set; }
        public string MARITAL { get; set; }
        public string SPOUSE { get; set; }
        public string MOBILE { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string BIRTH_PLACE { get; set; }
        public Nullable<decimal> EDUCAT { get; set; }
        public decimal DD_CODE { get; set; }
        public Nullable<decimal> RES_TYPE { get; set; }
        public Nullable<decimal> OCCUP { get; set; }
        public string GUAR_NAME { get; set; }
        public Nullable<decimal> GUAR_REL { get; set; }
        public Nullable<decimal> NATIONAL { get; set; }
        public Nullable<decimal> DEPEND { get; set; }
        public Nullable<decimal> BIRTH_CITY { get; set; }
        public Nullable<decimal> BIRTH_COUNTRY { get; set; }
        public Nullable<decimal> COS { get; set; }
        public string COS_ADD { get; set; }
        public Nullable<decimal> REL_PARTY { get; set; }
        public Nullable<decimal> REL_PARTY_CODE { get; set; }
        public string REL_PARTY_NAME { get; set; }
        public Nullable<decimal> REL_PARTY_REL { get; set; }
        public string NTK_NAME { get; set; }
        public Nullable<decimal> NTK_REL { get; set; }
        public string NTK_ADD { get; set; }
        public string NTK_PHONE { get; set; }
        public Nullable<decimal> NTK_CNIC { get; set; }
        public Nullable<System.DateTime> NTK_CNIC_EXPIRY { get; set; }
        public Nullable<decimal> BEN { get; set; }
        public Nullable<decimal> BEN_PARTY_CODE { get; set; }
        public string BEN_NAME { get; set; }
        public string BEN_ADDRESS { get; set; }
        public Nullable<decimal> BEN_CNIC { get; set; }
        public Nullable<decimal> BEN_OCCUP { get; set; }
        public Nullable<decimal> BEN_REL { get; set; }
        public string BUSS_NAME { get; set; }
        public Nullable<decimal> BUSS_TYPE { get; set; }
        public string BUSS_ADD { get; set; }
        public string BUSS_PHONE { get; set; }
        public Nullable<decimal> BUSS_NOY { get; set; }
        public Nullable<decimal> BUSS_NOE { get; set; }
        public string BUSS_NTN { get; set; }
        public Nullable<decimal> BUSS_APPROX_INCOME { get; set; }
        public string EMPL_NAME { get; set; }
        public Nullable<decimal> EMPL_TYPE { get; set; }
        public string EMPL_ADD { get; set; }
        public string EMPL_PHONE { get; set; }
        public string EMPL_DESIG { get; set; }
        public Nullable<System.DateTime> EMPL_DOJ { get; set; }
        public Nullable<decimal> EMPL_SERVICE_PERIOD { get; set; }
        public string EMPL_STATUS { get; set; }
        public Nullable<decimal> EMPL_APPROX_SAL { get; set; }
    }
}
