//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDD_CLIENT
    {
        public Nullable<System.DateTime> TRAN_DATE { get; set; }
        public string TYPE { get; set; }
        public string EVENT_TYPE { get; set; }
        public decimal PARTY_CODE { get; set; }
        public decimal DD_CODE { get; set; }
        public string CLIENT_TYPE { get; set; }
        public Nullable<decimal> TAX_RES_TYPE { get; set; }
        public Nullable<decimal> TAX_STATUS { get; set; }
        public Nullable<System.DateTime> TAX_EXPIRY { get; set; }
        public string TAX_EXEMPT_REASON { get; set; }
        public string DOC_TYPE { get; set; }
        public Nullable<decimal> CNIC { get; set; }
        public Nullable<System.DateTime> CNIC_EXPIRY { get; set; }
        public string PASS { get; set; }
        public Nullable<System.DateTime> PASS_EXPIRY { get; set; }
        public string CNIC_OTH { get; set; }
        public Nullable<System.DateTime> CNIC_OTH_EXPIRY { get; set; }
        public string NTN { get; set; }
        public Nullable<decimal> INCORP_COUNTRY { get; set; }
        public string INCORP_NO { get; set; }
        public Nullable<System.DateTime> INCORP_DATE { get; set; }
        public Nullable<decimal> IND { get; set; }
        public Nullable<decimal> CAT { get; set; }
        public Nullable<decimal> TITLE { get; set; }
        public string NAME { get; set; }
        public string ADD { get; set; }
        public string ADD_PERM { get; set; }
        public Nullable<decimal> ADD_CITY { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string FAX { get; set; }
        public Nullable<decimal> GROUP_CODE { get; set; }
        public string CONTACT_PERSON { get; set; }
        public string CONTACT_PERSON_DESIG { get; set; }
        public Nullable<decimal> RM_CODE { get; set; }
        public Nullable<decimal> ZAKAT_EXEMPT { get; set; }
        public string ZAKAT_EXEMPT_CERT { get; set; }
        public Nullable<decimal> ZAKAT_RATE { get; set; }
        public string DD_TYPE { get; set; }
        public string PEP_STATUS { get; set; }
        public string RISK_LEVEL { get; set; }
        public string BUSINESS { get; set; }
        public string KYC_STATUS { get; set; }
        public string FATCA_STATUS { get; set; }
        public string AUTH_STATUS { get; set; }
        public Nullable<System.DateTime> AUTH_DATE { get; set; }
        public Nullable<decimal> AUTH_BY { get; set; }
        public string AUTH_REMARKS { get; set; }
        public Nullable<decimal> INACTIVE_LMS { get; set; }
        public Nullable<decimal> INACTIVE_IMS { get; set; }
        public Nullable<decimal> INACTIVE_MFL { get; set; }
    }
}
