//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMS_CLIENT_LIMIT
    {
        public decimal TRAN_CODE { get; set; }
        public Nullable<System.DateTime> TRAN_DATE { get; set; }
        public decimal PARTY_CODE { get; set; }
        public Nullable<decimal> LEASE_CAT { get; set; }
        public Nullable<decimal> LIMIT_TYPE { get; set; }
        public Nullable<System.DateTime> EFFECT_DATE { get; set; }
        public Nullable<decimal> LIMIT { get; set; }
        public string AUTH_STATUS { get; set; }
        public Nullable<System.DateTime> AUTH_DATE { get; set; }
        public Nullable<decimal> AUTH_BY { get; set; }
        public string AUTH_REMARKS { get; set; }
        public Nullable<decimal> INACTIVE { get; set; }
    }
}
