//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BMSEntities : DbContext
    {
        public BMSEntities()
            : base("name=BMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADM_AUTH_STATUS> ADM_AUTH_STATUS { get; set; }
        public virtual DbSet<ADM_DAILY_KIBOR> ADM_DAILY_KIBOR { get; set; }
        public virtual DbSet<ADM_DEF_BANK> ADM_DEF_BANK { get; set; }
        public virtual DbSet<ADM_DEF_BANK_AC_TYPE> ADM_DEF_BANK_AC_TYPE { get; set; }
        public virtual DbSet<ADM_DEF_BANK_BR> ADM_DEF_BANK_BR { get; set; }
        public virtual DbSet<ADM_DEF_BRANCH> ADM_DEF_BRANCH { get; set; }
        public virtual DbSet<ADM_DEF_BUS_TYPE> ADM_DEF_BUS_TYPE { get; set; }
        public virtual DbSet<ADM_DEF_CHQ_TYPE> ADM_DEF_CHQ_TYPE { get; set; }
        public virtual DbSet<ADM_DEF_CITY> ADM_DEF_CITY { get; set; }
        public virtual DbSet<ADM_DEF_CLIENT_TYPE> ADM_DEF_CLIENT_TYPE { get; set; }
        public virtual DbSet<ADM_DEF_COUNTRY> ADM_DEF_COUNTRY { get; set; }
        public virtual DbSet<ADM_DEF_DD_TYPE> ADM_DEF_DD_TYPE { get; set; }
        public virtual DbSet<ADM_DEF_DOC_TYPE> ADM_DEF_DOC_TYPE { get; set; }
        public virtual DbSet<ADM_DEF_EDU> ADM_DEF_EDU { get; set; }
        public virtual DbSet<ADM_DEF_EMAIL_SETTINGS> ADM_DEF_EMAIL_SETTINGS { get; set; }
        public virtual DbSet<ADM_DEF_FINYEAR> ADM_DEF_FINYEAR { get; set; }
        public virtual DbSet<ADM_DEF_FLOAT> ADM_DEF_FLOAT { get; set; }
        public virtual DbSet<ADM_DEF_FLOAT_FREQ> ADM_DEF_FLOAT_FREQ { get; set; }
        public virtual DbSet<ADM_DEF_GENDER> ADM_DEF_GENDER { get; set; }
        public virtual DbSet<ADM_DEF_GROUP> ADM_DEF_GROUP { get; set; }
        public virtual DbSet<ADM_DEF_INSU_CO> ADM_DEF_INSU_CO { get; set; }
        public virtual DbSet<ADM_DEF_KIBOR_FREQ> ADM_DEF_KIBOR_FREQ { get; set; }
        public virtual DbSet<ADM_DEF_KIBOR_MONT> ADM_DEF_KIBOR_MONT { get; set; }
        public virtual DbSet<ADM_DEF_LOAN_TERM> ADM_DEF_LOAN_TERM { get; set; }
        public virtual DbSet<ADM_DEF_MARITAL> ADM_DEF_MARITAL { get; set; }
        public virtual DbSet<ADM_DEF_NATIONAL> ADM_DEF_NATIONAL { get; set; }
        public virtual DbSet<ADM_DEF_OCCUP> ADM_DEF_OCCUP { get; set; }
        public virtual DbSet<ADM_DEF_PEP> ADM_DEF_PEP { get; set; }
        public virtual DbSet<ADM_DEF_PROV> ADM_DEF_PROV { get; set; }
        public virtual DbSet<ADM_DEF_REL> ADM_DEF_REL { get; set; }
        public virtual DbSet<ADM_DEF_REL_PARTY> ADM_DEF_REL_PARTY { get; set; }
        public virtual DbSet<ADM_DEF_RES_TYPE> ADM_DEF_RES_TYPE { get; set; }
        public virtual DbSet<ADM_DEF_RM> ADM_DEF_RM { get; set; }
        public virtual DbSet<ADM_DEF_STOCK_TYPE> ADM_DEF_STOCK_TYPE { get; set; }
        public virtual DbSet<ADM_DEF_TAX_RES_TYPE> ADM_DEF_TAX_RES_TYPE { get; set; }
        public virtual DbSet<ADM_DEF_TAX_STATUS> ADM_DEF_TAX_STATUS { get; set; }
        public virtual DbSet<ADM_DEF_TITLE> ADM_DEF_TITLE { get; set; }
        public virtual DbSet<ADM_MDL> ADM_MDL { get; set; }
        public virtual DbSet<ADM_MDL_RIGHT> ADM_MDL_RIGHT { get; set; }
        public virtual DbSet<ADM_PASS_HISTORY> ADM_PASS_HISTORY { get; set; }
        public virtual DbSet<ADM_SETUP> ADM_SETUP { get; set; }
        public virtual DbSet<ADM_USER_BRANCH> ADM_USER_BRANCH { get; set; }
        public virtual DbSet<ADM_USER_LEVEL> ADM_USER_LEVEL { get; set; }
        public virtual DbSet<ADM_USER_LEVEL_RIGHTS> ADM_USER_LEVEL_RIGHTS { get; set; }
        public virtual DbSet<ADM_USER_MDL> ADM_USER_MDL { get; set; }
        public virtual DbSet<ADM_USER_RIGHT> ADM_USER_RIGHT { get; set; }
        public virtual DbSet<ADM_USER_RIGHTS> ADM_USER_RIGHTS { get; set; }
        public virtual DbSet<ADM_USERS> ADM_USERS { get; set; }
        public virtual DbSet<CDD_CLIENT> CDD_CLIENT { get; set; }
        public virtual DbSet<CDD_CLIENT_BANK> CDD_CLIENT_BANK { get; set; }
        public virtual DbSet<CDD_CLIENT_CON> CDD_CLIENT_CON { get; set; }
        public virtual DbSet<CDD_CLIENT_DIR> CDD_CLIENT_DIR { get; set; }
        public virtual DbSet<CDD_CLIENT_GUA> CDD_CLIENT_GUA { get; set; }
        public virtual DbSet<CDD_CLIENT_NATIONAL> CDD_CLIENT_NATIONAL { get; set; }
        public virtual DbSet<LMS_CLIENT_LIMIT> LMS_CLIENT_LIMIT { get; set; }
        public virtual DbSet<LMS_DEF_AMORT_TYPE> LMS_DEF_AMORT_TYPE { get; set; }
        public virtual DbSet<LMS_DEF_ASET_CAT> LMS_DEF_ASET_CAT { get; set; }
        public virtual DbSet<LMS_DEF_ASET_MAKE> LMS_DEF_ASET_MAKE { get; set; }
        public virtual DbSet<LMS_DEF_ASET_MANUFACT> LMS_DEF_ASET_MANUFACT { get; set; }
        public virtual DbSet<LMS_DEF_ASET_TYPE> LMS_DEF_ASET_TYPE { get; set; }
        public virtual DbSet<LMS_DEF_BCA_APPLI_TYPE> LMS_DEF_BCA_APPLI_TYPE { get; set; }
        public virtual DbSet<LMS_DEF_BCA_FACI_TYPE> LMS_DEF_BCA_FACI_TYPE { get; set; }
        public virtual DbSet<LMS_DEF_BCA_RENEWAL> LMS_DEF_BCA_RENEWAL { get; set; }
        public virtual DbSet<LMS_DEF_BCA_TYPES> LMS_DEF_BCA_TYPES { get; set; }
        public virtual DbSet<LMS_DEF_BRWR_TYPE> LMS_DEF_BRWR_TYPE { get; set; }
        public virtual DbSet<LMS_DEF_BUS_CAT> LMS_DEF_BUS_CAT { get; set; }
        public virtual DbSet<LMS_DEF_BUS_TYPE> LMS_DEF_BUS_TYPE { get; set; }
        public virtual DbSet<LMS_DEF_CAT> LMS_DEF_CAT { get; set; }
        public virtual DbSet<LMS_DEF_CIB_BRWR_TYPE> LMS_DEF_CIB_BRWR_TYPE { get; set; }
        public virtual DbSet<LMS_DEF_CIB_BUS_CAT> LMS_DEF_CIB_BUS_CAT { get; set; }
        public virtual DbSet<LMS_DEF_CIB_BUS_TYPE> LMS_DEF_CIB_BUS_TYPE { get; set; }
        public virtual DbSet<LMS_DEF_CIB_IND> LMS_DEF_CIB_IND { get; set; }
        public virtual DbSet<LMS_DEF_CIB_PROD> LMS_DEF_CIB_PROD { get; set; }
        public virtual DbSet<LMS_DEF_CIB_PROV> LMS_DEF_CIB_PROV { get; set; }
        public virtual DbSet<LMS_DEF_CIB_SECT> LMS_DEF_CIB_SECT { get; set; }
        public virtual DbSet<LMS_DEF_CIB_STATUS> LMS_DEF_CIB_STATUS { get; set; }
        public virtual DbSet<LMS_DEF_CIB_TYPE> LMS_DEF_CIB_TYPE { get; set; }
        public virtual DbSet<LMS_DEF_COLAT_TYPE> LMS_DEF_COLAT_TYPE { get; set; }
        public virtual DbSet<LMS_DEF_CORP_STAT> LMS_DEF_CORP_STAT { get; set; }
        public virtual DbSet<LMS_DEF_CORP_TYPE> LMS_DEF_CORP_TYPE { get; set; }
        public virtual DbSet<LMS_DEF_EDU> LMS_DEF_EDU { get; set; }
        public virtual DbSet<LMS_DEF_EMPL_STATUS> LMS_DEF_EMPL_STATUS { get; set; }
        public virtual DbSet<LMS_DEF_EMPL_TYPE> LMS_DEF_EMPL_TYPE { get; set; }
        public virtual DbSet<LMS_DEF_FACILITY_TYPE> LMS_DEF_FACILITY_TYPE { get; set; }
        public virtual DbSet<LMS_DEF_GROUP> LMS_DEF_GROUP { get; set; }
        public virtual DbSet<LMS_DEF_IND> LMS_DEF_IND { get; set; }
        public virtual DbSet<LMS_DEF_IND_TYPE> LMS_DEF_IND_TYPE { get; set; }
        public virtual DbSet<LMS_DEF_ISIC> LMS_DEF_ISIC { get; set; }
        public virtual DbSet<LMS_DEF_LEASE_NAT> LMS_DEF_LEASE_NAT { get; set; }
        public virtual DbSet<LMS_DEF_LEASE_NAT_SUB> LMS_DEF_LEASE_NAT_SUB { get; set; }
        public virtual DbSet<LMS_DEF_LEASE_TYPE> LMS_DEF_LEASE_TYPE { get; set; }
        public virtual DbSet<LMS_DEF_LEASE_TYPE_SUB> LMS_DEF_LEASE_TYPE_SUB { get; set; }
        public virtual DbSet<LMS_DEF_LEND_INST> LMS_DEF_LEND_INST { get; set; }
        public virtual DbSet<LMS_DEF_LESSEE_TYPE> LMS_DEF_LESSEE_TYPE { get; set; }
        public virtual DbSet<LMS_DEF_LITI_TYPE> LMS_DEF_LITI_TYPE { get; set; }
        public virtual DbSet<LMS_DEF_NFBI_SECT> LMS_DEF_NFBI_SECT { get; set; }
        public virtual DbSet<LMS_DEF_NICODE> LMS_DEF_NICODE { get; set; }
        public virtual DbSet<LMS_DEF_NP_TYPE> LMS_DEF_NP_TYPE { get; set; }
        public virtual DbSet<LMS_DEF_PAY_MODE> LMS_DEF_PAY_MODE { get; set; }
        public virtual DbSet<LMS_DEF_PERIOD> LMS_DEF_PERIOD { get; set; }
        public virtual DbSet<LMS_DEF_PROV> LMS_DEF_PROV { get; set; }
        public virtual DbSet<LMS_DEF_RENT_MODE> LMS_DEF_RENT_MODE { get; set; }
        public virtual DbSet<LMS_DEF_RES_TYPE> LMS_DEF_RES_TYPE { get; set; }
        public virtual DbSet<LMS_DEF_SECTOR> LMS_DEF_SECTOR { get; set; }
        public virtual DbSet<LMS_DEF_SUP> LMS_DEF_SUP { get; set; }
        public virtual DbSet<LMS_DEF_TITLE> LMS_DEF_TITLE { get; set; }
        public virtual DbSet<LMS_DEF_VALUATOR> LMS_DEF_VALUATOR { get; set; }
    }
}
